//! Cascaded PID controllers for attitude and body-rate control.

use control::PidController;
use fugit::MicrosDurationU32;
use math::{EulerAngles, Vec3, wrap_pi};

/// How the outer-loop error should be interpreted.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum AxisErrorMode {
    /// Use a plain subtraction `setpoint - measurement`.
    Linear,
    /// Wrap the angle error into `[-pi, pi]`.
    WrappedAngle,
}

/// One cascaded control axis.
///
/// The outer PID converts an angle error into a desired body-rate command.
/// The inner PID converts that desired body rate into an actuator command.
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct CascadeAxis {
    /// Outer-loop attitude PID.
    pub attitude_pid: PidController,
    /// Inner-loop body-rate PID.
    pub rate_pid: PidController,
    /// Absolute limit applied to the desired rate output of the outer loop.
    pub rate_limit_rad_s: f32,
    /// Error interpretation for the outer loop.
    pub error_mode: AxisErrorMode,
}

impl CascadeAxis {
    /// Creates a cascaded axis with a linear outer-loop error model.
    pub const fn new(
        attitude_pid: PidController,
        rate_pid: PidController,
        rate_limit_rad_s: f32,
    ) -> Self {
        Self {
            attitude_pid,
            rate_pid,
            rate_limit_rad_s,
            error_mode: AxisErrorMode::Linear,
        }
    }

    /// Changes how the outer-loop error is computed.
    pub fn with_error_mode(mut self, error_mode: AxisErrorMode) -> Self {
        self.error_mode = error_mode;
        self
    }

    /// Updates the outer-loop rate limit.
    pub fn set_rate_limit(&mut self, rate_limit_rad_s: f32) {
        self.rate_limit_rad_s = rate_limit_rad_s.abs();
    }

    /// Resets both PID loops.
    pub fn reset(&mut self) {
        self.attitude_pid.reset();
        self.rate_pid.reset();
    }

    /// Runs the full cascade for one attitude-controlled axis.
    ///
    /// Returns `(desired_rate_rad_s, actuator_command)`.
    pub fn update_attitude(
        &mut self,
        target_angle_rad: f32,
        measured_angle_rad: f32,
        measured_rate_rad_s: f32,
        dt: MicrosDurationU32,
    ) -> (f32, f32) {
        let desired_rate_rad_s = match self.error_mode {
            AxisErrorMode::Linear => {
                self.attitude_pid
                    .update(target_angle_rad, measured_angle_rad, dt)
            }
            AxisErrorMode::WrappedAngle => {
                let error = wrap_pi(target_angle_rad - measured_angle_rad);
                // Feeding `-error` as the measurement makes the PID see the desired
                // wrapped error while keeping the existing controller implementation.
                self.attitude_pid.update(0.0, -error, dt)
            }
        }
        .clamp(-self.rate_limit_rad_s, self.rate_limit_rad_s);

        let actuator_command = self
            .rate_pid
            .update(desired_rate_rad_s, measured_rate_rad_s, dt);
        (desired_rate_rad_s, actuator_command)
    }

    /// Runs only the inner rate loop, useful for acro / rate mode.
    pub fn update_rate(
        &mut self,
        target_rate_rad_s: f32,
        measured_rate_rad_s: f32,
        dt: MicrosDurationU32,
    ) -> f32 {
        self.rate_pid
            .update(target_rate_rad_s, measured_rate_rad_s, dt)
    }
}

/// Output of the cascaded controller.
#[derive(Copy, Clone, Debug, Default, PartialEq)]
pub struct CascadeOutputs {
    /// Final actuator commands from the inner loop.
    pub actuator: Vec3,
    /// Desired body-rate commands generated by the outer loop.
    pub desired_rates_rad_s: Vec3,
}

/// Three-axis cascaded attitude controller.
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct CascadeAttitudeController {
    /// Roll axis controller.
    pub roll: CascadeAxis,
    /// Pitch axis controller.
    pub pitch: CascadeAxis,
    /// Yaw axis controller.
    pub yaw: CascadeAxis,
}

impl CascadeAttitudeController {
    /// Creates a new three-axis cascaded controller.
    pub const fn new(roll: CascadeAxis, pitch: CascadeAxis, yaw: CascadeAxis) -> Self {
        Self { roll, pitch, yaw }
    }

    /// Resets all controller state.
    pub fn reset(&mut self) {
        self.roll.reset();
        self.pitch.reset();
        self.yaw.reset();
    }

    /// Runs three cascaded attitude loops using Euler angles and body rates.
    ///
    /// Roll, pitch, and yaw targets are interpreted as absolute attitudes.
    /// Yaw wrapping is enabled automatically if the yaw axis is configured with
    /// [`AxisErrorMode::WrappedAngle`].
    pub fn update_attitude(
        &mut self,
        target_attitude: EulerAngles,
        measured_attitude: EulerAngles,
        measured_rates_rad_s: Vec3,
        dt: MicrosDurationU32,
    ) -> CascadeOutputs {
        let (roll_rate, roll_out) = self.roll.update_attitude(
            target_attitude.roll,
            measured_attitude.roll,
            measured_rates_rad_s.x,
            dt,
        );
        let (pitch_rate, pitch_out) = self.pitch.update_attitude(
            target_attitude.pitch,
            measured_attitude.pitch,
            measured_rates_rad_s.y,
            dt,
        );
        let (yaw_rate, yaw_out) = self.yaw.update_attitude(
            target_attitude.yaw,
            measured_attitude.yaw,
            measured_rates_rad_s.z,
            dt,
        );

        CascadeOutputs {
            actuator: Vec3::new(roll_out, pitch_out, yaw_out),
            desired_rates_rad_s: Vec3::new(roll_rate, pitch_rate, yaw_rate),
        }
    }

    /// Fixed-wing convenience update.
    ///
    /// Roll and pitch are angle-controlled, while yaw is rate-controlled, which
    /// is often a more natural mode for RC aircraft.
    pub fn update_fixed_wing(
        &mut self,
        target_roll_rad: f32,
        target_pitch_rad: f32,
        target_yaw_rate_rad_s: f32,
        measured_attitude: EulerAngles,
        measured_rates_rad_s: Vec3,
        dt: MicrosDurationU32,
    ) -> CascadeOutputs {
        let (roll_rate, roll_out) = self.roll.update_attitude(
            target_roll_rad,
            measured_attitude.roll,
            measured_rates_rad_s.x,
            dt,
        );
        let (pitch_rate, pitch_out) = self.pitch.update_attitude(
            target_pitch_rad,
            measured_attitude.pitch,
            measured_rates_rad_s.y,
            dt,
        );
        let yaw_out = self
            .yaw
            .update_rate(target_yaw_rate_rad_s, measured_rates_rad_s.z, dt);

        CascadeOutputs {
            actuator: Vec3::new(roll_out, pitch_out, yaw_out),
            desired_rates_rad_s: Vec3::new(roll_rate, pitch_rate, target_yaw_rate_rad_s),
        }
    }

    /// Rate-mode update for all three axes.
    pub fn update_rates(
        &mut self,
        target_rates_rad_s: Vec3,
        measured_rates_rad_s: Vec3,
        dt: MicrosDurationU32,
    ) -> Vec3 {
        Vec3::new(
            self.roll
                .update_rate(target_rates_rad_s.x, measured_rates_rad_s.x, dt),
            self.pitch
                .update_rate(target_rates_rad_s.y, measured_rates_rad_s.y, dt),
            self.yaw
                .update_rate(target_rates_rad_s.z, measured_rates_rad_s.z, dt),
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_axis() -> CascadeAxis {
        let mut attitude = PidController::new(4.0, 0.0, 0.0);
        attitude.set_output_limits(-10.0, 10.0);

        let mut rate = PidController::new(0.5, 0.0, 0.0);
        rate.set_output_limits(-1.0, 1.0);

        CascadeAxis::new(attitude, rate, 3.0)
    }

    #[test]
    fn zero_error_produces_zero_output() {
        let mut controller = CascadeAttitudeController::new(make_axis(), make_axis(), make_axis());
        let output = controller.update_attitude(
            EulerAngles::new(0.0, 0.0, 0.0),
            EulerAngles::new(0.0, 0.0, 0.0),
            Vec3::zero(),
            MicrosDurationU32::from_millis(10),
        );
        assert_eq!(output.actuator, Vec3::zero());
        assert_eq!(output.desired_rates_rad_s, Vec3::zero());
    }

    #[test]
    fn positive_roll_error_produces_positive_roll_command() {
        let mut controller = CascadeAttitudeController::new(make_axis(), make_axis(), make_axis());
        let output = controller.update_attitude(
            EulerAngles::new(0.2, 0.0, 0.0),
            EulerAngles::new(0.0, 0.0, 0.0),
            Vec3::zero(),
            MicrosDurationU32::from_millis(10),
        );
        assert!(output.desired_rates_rad_s.x > 0.0);
        assert!(output.actuator.x > 0.0);
    }

    #[test]
    fn yaw_error_wraps_across_pi() {
        let mut yaw = make_axis().with_error_mode(AxisErrorMode::WrappedAngle);
        let (desired_rate, _) = yaw.update_attitude(
            -core::f32::consts::PI + 0.1,
            core::f32::consts::PI - 0.1,
            0.0,
            MicrosDurationU32::from_millis(10),
        );
        assert!(desired_rate > 0.0);
    }

    #[test]
    fn fixed_wing_mode_uses_yaw_rate_directly() {
        let mut controller = CascadeAttitudeController::new(make_axis(), make_axis(), make_axis());
        let output = controller.update_fixed_wing(
            0.0,
            0.0,
            0.6,
            EulerAngles::new(0.0, 0.0, 0.0),
            Vec3::zero(),
            MicrosDurationU32::from_millis(10),
        );
        assert_eq!(output.desired_rates_rad_s.z, 0.6);
        assert!(output.actuator.z > 0.0);
    }
}
