[package]
name = "imu"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
embedded-hal = { workspace = true }
eskf = { path = "../eskf" }
fugit = { workspace = true }
glam = { workspace = true }
libm = { workspace = true }
madgwick = { path = "../madgwick" }

[dev-dependencies]
lis3mdl = { path = "../lis3mdl" }

[target.'thumbv8m.main-none-eabihf'.dependencies]
defmt = { workspace = true }
defmt-rtt = { workspace = true }
linked_list_allocator = "0.10"
lis3mdl = { path = "../lis3mdl" }
lps25hb = { path = "../lps25hb" }
lsm6ds3tr = "0.2"
panic-probe = { workspace = true }

[target.'thumbv8m.main-none-eabihf'.dependencies.rp235x-hal]
version = "0.4"
features = ["binary-info", "critical-section-impl", "rt"]
